sudo: required

language: bash

services:
  - docker

env:
  - VERSION=3.3.0
  - VERSION=3.2.2
  - VERSION=3.2.0

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

before_script:
  - env | sort
  - cd "$VERSION"
  - DOCKER_IMAGE="curator"

script:
  - docker build -t ${DOCKER_IMAGE}:${VERSION} .
  - bats tests
